/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edu.sise.gui;

import com.edu.sise.entidades.Compra;
import com.edu.sise.entidades.Productos;
import com.edu.sise.logic.CompraLogic;
import com.edu.sise.logic.ProductosLogic;
import javax.swing.JOptionPane;

/**
 *
 * @author CLIENTE
 */
public class ifrmCompra extends javax.swing.JInternalFrame {

    
    private CompraLogic logica;
    private ProductosLogic logicaProd;
    
    
    /**
     * Creates new form ifrmCompra
     */
    public ifrmCompra() {
        initComponents();
        
          logica = new CompraLogic();
        logicaProd = new ProductosLogic();

        //llenar el combo Provincia al iniciar el ifrm
        logicaProd.llenarComboProductos(cboProductos);
        //logicaDepa.llenarDepartamento(cboDepartamentos);
        logica.imprimir(tbLista);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtClie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboProductos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtCate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrec = new javax.swing.JTextField();
        txtCant = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdProd = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnListar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnModi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnGua = new javax.swing.JButton();
        btnElim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTot = new javax.swing.JTextField();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos de provincias"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClieActionPerformed(evt);
            }
        });
        jPanel2.add(txtClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 80, 30));

        jLabel4.setText("CLIENTE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtId.setEditable(false);
        txtId.setBackground(java.awt.SystemColor.inactiveCaption);
        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 69, 30));

        jLabel1.setText("PRODUCTOS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jPanel2.add(cboProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 180, 30));

        jLabel5.setText("CATEGORÍA");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtCate.setEnabled(false);
        jPanel2.add(txtCate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 80, 30));

        jLabel6.setText("PRECIO");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        txtPrec.setEnabled(false);
        jPanel2.add(txtPrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 80, 30));
        jPanel2.add(txtCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 80, 30));

        jLabel8.setText("CANTIDAD");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jLabel9.setText("ID PRODUCTO");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        txtIdProd.setEnabled(false);
        jPanel2.add(txtIdProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 80, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jPanel1.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 169, 130, 55));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edu/sise/gui/resources/salirr.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, 60));

        btnModi.setText("Modificar");
        btnModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModiActionPerformed(evt);
            }
        });
        jPanel1.add(btnModi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 130, 57));

        jButton1.setText("IMPRIMIR");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 130, 52));

        btnGua.setText("Guardar");
        btnGua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGua, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 50));

        btnElim.setText("Eliminar");
        btnElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimActionPerformed(evt);
            }
        });
        jPanel1.add(btnElim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, 50));

        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLista);

        jLabel2.setText("BUSCAR COMPRA");

        jLabel7.setText("TOTAL DE LA COMPRA");

        txtTot.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTot)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClieActionPerformed

    }//GEN-LAST:event_txtClieActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed

        tbLista.setModel(new CompraLogic().getModelo());
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModiActionPerformed

      Compra o = new Compra(
          Integer.parseInt((txtId.getText().isEmpty())?"-1":txtId.getText()),
                
        txtClie.getText(),
        txtCate.getText(),
        txtIdProd.getText(),
   Double.parseDouble(txtPrec.getText()),
   //txtIdProd.getText(),
                Integer.parseInt(txtCant.getText()),
((Productos)cboProductos.getSelectedItem()).getId_prod());
        
        boolean rpta = logica.modificarCompra(o);
        if (rpta){
            JOptionPane.showMessageDialog(this, "Se modifico correctamente :)");
        }
        else{
            JOptionPane.showMessageDialog(this, "No se pudo modificar :( ");
        }
        logica.imprimir(tbLista);
    }//GEN-LAST:event_btnModiActionPerformed

    private void tbListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaMouseClicked
        //variables
        int fila = -1;
        int id_com = 0;
        int id_prod = 0;
        int cant = 0;
        double prec = 0;
        String clien ="";
        String cate ="";
     
         fila = tbLista.getSelectedRow();
int x=0;
        //procese y salida
        if (fila>=0) {
            id_com=Integer.parseInt( tbLista.getValueAt(fila, x++) +"");
            clien=tbLista.getValueAt(fila, x++)+"";
            cate=tbLista.getValueAt(fila, x++)+"";
            prec= Double.parseDouble(tbLista.getValueAt(fila, x++)+"");  
id_prod=Integer.parseInt( tbLista.getValueAt(fila, x++) +"");
cant=Integer.parseInt( tbLista.getValueAt(fila, x++) +"");

        txtId.setText(id_com+"");
        txtClie.setText(clien);
        txtCate.setText(cate);
        txtPrec.setText(prec+"");
        txtIdProd.setText(id_prod+"");

        logicaProd.seleccionarItemCbo(cboProductos, id_prod);

       // logicaTutor.seleccionarItemCbo(cboDepartamentos.getSelectedItem()).get;
logica.imprimir(tbLista);
    }//GEN-LAST:event_tbListaMouseClicked

    private void btnGuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuaActionPerformed

Compra o = new Compra(
          Integer.parseInt((txtId.getText().isEmpty())?"-1":txtId.getText()),
                
        txtClie.getText(),
        txtCate.getText(),
        txtIdProd.getText(),
   Double.parseDouble(txtPrec.getText()),
   //txtIdProd.getText(),
                Integer.parseInt(txtCant.getText()),
((Productos)cboProductos.getSelectedItem()).getId_prod());
        
        
        
        boolean rpta = logica.agegarCompra(o);
        if (rpta){
            JOptionPane.showMessageDialog(this, "Se registro correctamente ");
        }
        else{
            JOptionPane.showMessageDialog(this, "No se pudo registrar correctamente ");
        }

        logica.imprimir(tbLista);

    }//GEN-LAST:event_btnGuaActionPerformed

    private void btnElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimActionPerformed
       
int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea realmente eliminar la compra?", "SISTEMAS", JOptionPane.YES_NO_OPTION);

        if(respuesta == JOptionPane.YES_OPTION){
            int id_depa = Integer.parseInt(txtId.getText());
            boolean rpta = logica.eliminarCompra(id_depa);
            if(rpta){
                JOptionPane.showMessageDialog(this, "Se elimino correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo elimino");
            }
        }
        logica.imprimir(tbLista);
        

        
    }//GEN-LAST:event_btnElimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElim;
    private javax.swing.JButton btnGua;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModi;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboProductos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbLista;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCate;
    private javax.swing.JTextField txtClie;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdProd;
    private javax.swing.JTextField txtPrec;
    private javax.swing.JTextField txtTot;
    // End of variables declaration//GEN-END:variables
}
