/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.edu.sise.gui;

import com.edu.sise.dao.ProveedorDao;
import com.edu.sise.entidades.Proveedor;
import com.edu.sise.logic.ProveedorLogic;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;



public class ifrmProveedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmProveedores
     */
    ProveedorLogic logica;
    public ifrmProveedores() {
        initComponents();
        logica = new ProveedorLogic();
        logica.imprimir(tbLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        txtHoras_trabajo = new javax.swing.JTextField();
        txtNum_prod_entregados = new javax.swing.JTextField();
        txtNum_boletas_entregados = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLsitar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        btnImprimir = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ingrese Datos"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Dni");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setText("horas_trabajo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel4.setText("num_prod_entregados");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel5.setText("Num_boletas_entregados");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setText("Apellido");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel7.setText("Nombre");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel8.setText("ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 90, -1));
        jPanel1.add(txtHoras_trabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 90, -1));
        jPanel1.add(txtNum_prod_entregados, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 90, -1));
        jPanel1.add(txtNum_boletas_entregados, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 90, -1));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 160, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 160, -1));

        txtId.setEditable(false);
        txtId.setBackground(java.awt.SystemColor.inactiveCaption);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 90, -1));

        jLabel9.setText("sueldo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        jPanel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 300));

        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 510, 130));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 100, 40));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 100, 40));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 100, 40));

        btnLsitar.setText("Listar");
        btnLsitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLsitarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLsitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 100, 40));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 100, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Busqueda"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });
        jPanel2.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 240, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 360, 90));

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        boolean rpta;
        rpta = logica.agregarProveedor(new Proveedor(
                -1,
                txtDni.getText(),
                txtNombre.getText(),
                txtApellido.getText(),
                Integer.parseInt(txtNum_boletas_entregados.getText()),
                Integer.parseInt(txtNum_prod_entregados.getText()),
                Integer.parseInt(txtHoras_trabajo.getText()),
                Double.parseDouble(txtSueldo.getText())
        ));
        if(rpta)
            JOptionPane.showMessageDialog(this, "Se registro correctamente");
        else 
            JOptionPane.showMessageDialog(this, "No se pudo agregar el registro");
        logica.imprimir(tbLista);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        boolean rpta;
        rpta = logica.modificarProveedor(new Proveedor(Integer.parseInt(
                txtId.getText()),
                txtDni.getText(),
                txtNombre.getText(),
                txtApellido.getText(),
                Integer.parseInt(txtNum_boletas_entregados.getText()),
                Integer.parseInt(txtNum_prod_entregados.getText()),
                Integer.parseInt(txtHoras_trabajo.getText()),
                Double.parseDouble(txtSueldo.getText())
        ));
        if(rpta)
            JOptionPane.showMessageDialog(this, "Se modifico correctamente");
        else
            JOptionPane.showMessageDialog(this, "No se pudo modificar el registro");
        logica.imprimir(tbLista);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        boolean rpta;
        int op ;
        
        op = JOptionPane.showConfirmDialog(this, "¿Desea realmente eliminar el registro?", "SISTEMA", JOptionPane.YES_NO_OPTION);
        
        if(op==JOptionPane.YES_OPTION){
            
        
        rpta = logica.eliminarProveedor(Integer.parseInt(txtId.getText()));
        if(rpta)
            JOptionPane.showMessageDialog(this,"Se elimino correctamente");
        else
            JOptionPane.showMessageDialog(this,"No se pudo eliminar el registro");
        }
        logica.imprimir(tbLista);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLsitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLsitarActionPerformed
        // TODO add your handling code here:
        logica.imprimir(tbLista);
    }//GEN-LAST:event_btnLsitarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tbListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaMouseClicked
        // TODO add your handling code here:
        int fila = -1;
        int id_proveedor= -1, num_boletas_entregados = -1,num_prod_entregados=-1,horas_trabajo=-1;
        String dni = "",nombre ="", apellido="";
        double sueldo=-1;
        
        fila = tbLista.getSelectedRow();
        if(fila>=0){
            int x =0;
            id_proveedor= Integer.parseInt(String.valueOf(tbLista.getValueAt(fila, x++)));
            dni = String.valueOf(tbLista.getValueAt(fila, x++));
            nombre = String.valueOf(tbLista.getValueAt(fila, x++));
            apellido = String.valueOf(tbLista.getValueAt(fila, x++));
            num_boletas_entregados = Integer.parseInt(String.valueOf(tbLista.getValueAt(fila, x++)));
            num_prod_entregados = Integer.parseInt(String.valueOf(tbLista.getValueAt(fila, x++)));
            horas_trabajo = Integer.parseInt(String.valueOf(tbLista.getValueAt(fila, x++)));
            sueldo= Double.parseDouble(String.valueOf(tbLista.getValueAt(fila, x++)));
        }
        txtId.setText(id_proveedor+"");
        txtDni.setText(dni);
        txtNombre.setText(nombre);
        txtApellido.setText(apellido);
        txtNum_boletas_entregados.setText(num_boletas_entregados+"");
        txtNum_prod_entregados.setText(num_prod_entregados+"");
        txtHoras_trabajo.setText(horas_trabajo+"");
        txtSueldo.setText(sueldo+"");
    }//GEN-LAST:event_tbListaMouseClicked

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
      logica.imprimir(tbLista, txtBusqueda.getText());
      
      
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        logica.generarReporte();
    }//GEN-LAST:event_btnImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLsitar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLista;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtHoras_trabajo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNum_boletas_entregados;
    private javax.swing.JTextField txtNum_prod_entregados;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
}
