/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edu.sise.gui;


import com.edu.sise.entidades.Cliente;
import com.edu.sise.logic.ClienteLogic;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class ifrmCliente extends javax.swing.JInternalFrame {

   private ClienteLogic logica;
   private ClienteLogic logicaCliente;
   
    public ifrmCliente() {
        initComponents();
        logica = new ClienteLogic();
        logicaCliente = new ClienteLogic();
        
        //llenar el combo Departamento al iniciar el ifrm
        logicaCliente.llenarComboCliente(cboSexo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnListar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGuard = new javax.swing.JButton();
        btnElim = new javax.swing.JButton();
        btnModi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        cboSexo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        txtDni1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtId1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cboSexo1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtApellidos1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnListar1 = new javax.swing.JButton();
        btnGuard1 = new javax.swing.JButton();
        btnElim1 = new javax.swing.JButton();
        btnModi1 = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones"));

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGuard.setText("Guardar");
        btnGuard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardActionPerformed(evt);
            }
        });

        btnElim.setText("Eliminar");
        btnElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimActionPerformed(evt);
            }
        });

        btnModi.setText("Modificar");
        btnModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuard, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnElim)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnElim, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del cliente"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("ID :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 130, -1));

        jLabel4.setText("NOMBRE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtId.setEditable(false);
        txtId.setBackground(java.awt.SystemColor.inactiveCaption);
        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 200, -1));

        jLabel1.setText("DNI :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel2.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 90, -1));

        jLabel2.setText("APELLIDOS :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel2.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 130, -1));

        cboSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSexoActionPerformed(evt);
            }
        });
        jPanel2.add(cboSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 110, -1));

        tbLista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLista);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Datos del cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(txtDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 90, -1));

        jLabel10.setText("DNI:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtId1.setEditable(false);
        txtId1.setBackground(java.awt.SystemColor.inactiveCaption);
        txtId1.setEnabled(false);
        txtId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId1ActionPerformed(evt);
            }
        });
        jPanel5.add(txtId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, -1));

        jLabel9.setText("ID:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 30, -1));

        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });
        jPanel5.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 130, -1));

        jLabel11.setText("NOMBRE:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        cboSexo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSexo1ActionPerformed(evt);
            }
        });
        jPanel5.add(cboSexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 110, -1));

        jLabel12.setText("APELLIDOS:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel5.add(txtApellidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 130, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnListar1.setText("Listar");
        btnListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListar1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnListar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 96, 75, 31));

        btnGuard1.setText("Guardar");
        btnGuard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuard1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnGuard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 60, 75, 30));

        btnElim1.setText("Eliminar");
        btnElim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElim1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnElim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 96, 93, 31));

        btnModi1.setText("Modificar");
        btnModi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModi1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnModi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 60, 83, 30));

        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 85, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed

        logica.imprimir(tbLista);
        // tbLista.setModel(new DepartamentoLogic().getModelo());
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardActionPerformed
        // TODO add your handling code here:
            Cliente o = new Cliente(
            Integer.parseInt((txtId.getText().isEmpty())?"-1":txtId.getText()),
            Integer.parseInt(txtDni.getText()),
            txtNombre.getText(),
            txtApellidos.getText(),
            ((Cliente)cboSexo.getSelectedItem()).getSexo()
                );
        boolean rpta = logica.agregarCliente(o);
        if(rpta){
            JOptionPane.showMessageDialog(this, "Se registro correctamente :) !!!");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo registrar :( !!!");
        }
        logica.imprimir(tbLista);
    }//GEN-LAST:event_btnGuardActionPerformed

    private void btnElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(
            this, "¿Desea realmente eliminar el registro?","SISTEMAS",JOptionPane.YES_NO_OPTION);

        if(respuesta == JOptionPane.YES_OPTION){
            int id = Integer.parseInt(txtId.getText());
            boolean rpta = logica.eliminarCliente(id);
            if(rpta){
                JOptionPane.showMessageDialog(this, "Se elimino correctamente :) !!!");
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo eliminar :( !!!");
            }
        }
        logica.imprimir(tbLista);
    }//GEN-LAST:event_btnElimActionPerformed

    private void btnModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModiActionPerformed
            Cliente o = new Cliente(
             Integer.parseInt((txtId.getText().isEmpty())?"-1":txtId.getText()),
            Integer.parseInt(txtDni.getText()),
            txtNombre.getText(),
            txtApellidos.getText(),
            ((Cliente)cboSexo.getSelectedItem()).getSexo()
        );
        boolean rpta = logica.modificarCliente(o);
        if(rpta){
            JOptionPane.showMessageDialog(this, "Se modifico correctamente :) !!!");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo modificar :( !!!");
        }
        logica.imprimir(tbLista);
    }//GEN-LAST:event_btnModiActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void cboSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSexoActionPerformed

    private void tbListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaMouseClicked
        //variables
        int fila = -1;
        int id_cliente = 0;
        int DNI = 0;
        String Nombre = "";
        String Apellidos = "";
        String Sexo = "";
        //entrada
        fila = tbLista.getSelectedRow();

        //proceso y salida
        if(fila>=0){
            id_cliente =Integer.parseInt(tbLista.getValueAt(fila, 0)+"");
            DNI =Integer.parseInt(tbLista.getValueAt(fila, 1)+"");
            Nombre =tbLista.getValueAt(fila, 2)+"";
            Apellidos =tbLista.getValueAt(fila, 3)+"";
            Sexo =tbLista.getValueAt(fila, 4)+"";
        }

        txtId.setText(id_cliente+"");
        txtDni.setText(DNI+"");
        txtNombre.setText(Nombre);
        txtApellidos.setText(Apellidos);
        logicaCliente.seleccionarItemCbo(cboSexo,Sexo);
    }//GEN-LAST:event_tbListaMouseClicked

    private void btnListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListar1ActionPerformed

        logica.imprimir(tbLista);
        // tbLista.setModel(new DepartamentoLogic().getModelo());
    }//GEN-LAST:event_btnListar1ActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnGuard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuard1ActionPerformed
        // TODO add your handling code here:
        Cliente o = new Cliente(   
            Integer.parseInt((txtId.getText().isEmpty())?"-1":txtId.getText()),
            Integer.parseInt(txtDni.getText()),
            txtNombre.getText(),
            txtApellidos.getText(),
            ((Cliente)cboSexo.getSelectedItem()).getSexo()
        );
        boolean rpta = logica.agregarCliente(o);
        if(rpta){
            JOptionPane.showMessageDialog(this, "Se registro correctamente :) !!!");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo registrar :( !!!");
        }
        logica.imprimir(tbLista);
    }//GEN-LAST:event_btnGuard1ActionPerformed

    private void btnElim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElim1ActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(
            this, "¿Desea realmente eliminar el registro?","SISTEMAS",JOptionPane.YES_NO_OPTION);

        if(respuesta == JOptionPane.YES_OPTION){
            int id = Integer.parseInt(txtId.getText());
            boolean rpta = logica.eliminarCliente(id);
            if(rpta){
                JOptionPane.showMessageDialog(this, "Se elimino correctamente :) !!!");
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo eliminar :( !!!");
            }
        }
        logica.imprimir(tbLista);
    }//GEN-LAST:event_btnElim1ActionPerformed

    private void btnModi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModi1ActionPerformed
        Cliente o = new Cliente(   
            Integer.parseInt((txtId.getText().isEmpty())?"-1":txtId.getText()),
            Integer.parseInt(txtDni.getText()),
            txtNombre.getText(),
            txtApellidos.getText(),
            ((Cliente)cboSexo.getSelectedItem()).getSexo()
        );
        boolean rpta = logica.modificarCliente(o);
        if(rpta){
            JOptionPane.showMessageDialog(this, "Se modifico correctamente :) !!!");
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo modificar :( !!!");
        }
        logica.imprimir(tbLista);
    }//GEN-LAST:event_btnModi1ActionPerformed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed

    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void txtId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId1ActionPerformed

    private void cboSexo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSexo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSexo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElim;
    private javax.swing.JButton btnElim1;
    private javax.swing.JButton btnGuard;
    private javax.swing.JButton btnGuard1;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnListar1;
    private javax.swing.JButton btnModi;
    private javax.swing.JButton btnModi1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JComboBox<String> cboSexo;
    private javax.swing.JComboBox<String> cboSexo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbLista;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtApellidos1;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDni1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    // End of variables declaration//GEN-END:variables
}
