/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edu.sise.gui;

import com.edu.sise.entidades.Productos;
import com.edu.sise.logic.ProductosLogic;
import com.edu.sise.utils.Utils;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author CLIENTE
 */
public class ifrmProductos extends javax.swing.JInternalFrame {

    private ProductosLogic logicaProd;
    
    
    
    
    public ifrmProductos() {
        initComponents();
        
        
        logicaProd = new ProductosLogic();
        
        logicaProd.imprimir(tbLis);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSto = new javax.swing.JTextField();
        txtPrec = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBus = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnGuard = new javax.swing.JButton();
        btnSali = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        btnModi = new javax.swing.JButton();
        btnImpr = new javax.swing.JButton();
        btnElim = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLis = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del producto"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NOMBRE DEL PRODUCTO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 140, 30));

        jLabel2.setText("CATEGORIA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 130, -1, -1));
        jPanel1.add(txtCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 123, 130, 28));

        jLabel3.setText("STOCK");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel4.setText("PRECIO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));
        jPanel1.add(txtSto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 73, 26));
        jPanel1.add(txtPrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 90, 28));

        txtId.setEnabled(false);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 67, 30));

        jLabel5.setText("ID PRODUCTO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        txtBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusActionPerformed(evt);
            }
        });
        txtBus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusKeyReleased(evt);
            }
        });
        jPanel1.add(txtBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 450, 40));

        jLabel6.setText("BUSCA TU PRODUCTO AQUI");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuard.setText("GUARDAR");
        btnGuard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, 60));

        btnSali.setText("SALIR");
        btnSali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaliActionPerformed(evt);
            }
        });
        jPanel2.add(btnSali, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 130, 57));

        btnList.setText("LISTAR");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });
        jPanel2.add(btnList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 60));

        btnModi.setText("MODIFICAR");
        btnModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModiActionPerformed(evt);
            }
        });
        jPanel2.add(btnModi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 133, 58));

        btnImpr.setText("IMPRIMIR");
        btnImpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprActionPerformed(evt);
            }
        });
        jPanel2.add(btnImpr, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 133, 60));

        btnElim.setText("ELIMINAR");
        btnElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimActionPerformed(evt);
            }
        });
        jPanel2.add(btnElim, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 130, 61));

        jButton1.setText("CARGA MASIVA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 130, 50));

        tbLis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbLis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLis);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaliActionPerformed
this.dispose(); 
    }//GEN-LAST:event_btnSaliActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
         //listar     
        tbLis.setModel(new ProductosLogic().getModelo());
        
        
    }//GEN-LAST:event_btnListActionPerformed

    private void btnGuardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardActionPerformed
      
        
        //guardar
   
         
        if (txtNombre.getText().isEmpty() || txtCat.getText().isEmpty() || txtSto.getText().isEmpty() || 
            txtPrec.getText().isEmpty()   )
        {
            
         JOptionPane.showMessageDialog(this,"Por favor complete todos los datos");
        }
        
        else
        {
            
        Productos o = new Productos(
Integer.parseInt((txtId.getText().isEmpty())?"-1":txtId.getText()),
      
        txtNombre.getText(),
   txtCat.getText(),
   Integer.parseInt(txtSto.getText()),
   Double.parseDouble(txtPrec.getText() 
   ));
 
 
        if(validaCampos())
    return;
boolean rpta = logicaProd.agegarProductos(o);

if (rpta){
            JOptionPane.showMessageDialog(this, "El producto se registró correctamente");
        }
        else{
            JOptionPane.showMessageDialog(this, "El producto no se registró ");
        }


logicaProd.imprimir(tbLis);
        }

        
    }//GEN-LAST:event_btnGuardActionPerformed

    private void btnElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimActionPerformed
       
      
         int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea realmente eliminar este producto?", "SISTEMAS", JOptionPane.YES_NO_OPTION);
     
        if(respuesta == JOptionPane.YES_OPTION){
            int id_prod = Integer.parseInt(txtId.getText());
            boolean rpta = logicaProd.eliminarProductos(id_prod);
            if(rpta){
                JOptionPane.showMessageDialog(this, "Se elimino con éxito");
            } else {
                JOptionPane.showMessageDialog(this, "No se elimino el producto");
            }
        }
        logicaProd.imprimir(tbLis);
    }//GEN-LAST:event_btnElimActionPerformed

    private void btnModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModiActionPerformed
     
        
        Productos o = new Productos(
                 Integer.parseInt((txtId.getText().isEmpty())?"-1":txtId.getText()),
                 txtNombre.getText(),
   txtCat.getText(),
   Integer.parseInt(txtSto.getText()),
   Double.parseDouble(txtPrec.getText() 
   ));
        boolean rpta = logicaProd.modificarProductos(o);
        if (rpta){
            JOptionPane.showMessageDialog(this, "El registro se a modificado correctamente");
        }
        else{
            JOptionPane.showMessageDialog(this, "No se pudo modificar el registro");
        }
        
        
        
        
    }//GEN-LAST:event_btnModiActionPerformed

    private void tbLisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLisMouseClicked


 int fila = -1;
        int id_prod = 0;
        String nombre ="";
        String cat ="";
        int sto=0;
        double prec=0;
        
        
        //entrada
        fila = tbLis.getSelectedRow();
        
        //procese y salida
        int x=0;
        if (fila>=0) {
            id_prod=Integer.parseInt( tbLis.getValueAt(fila, x++) +"");
            nombre=tbLis.getValueAt(fila, x++)+"";
            cat=tbLis.getValueAt(fila, x++)+"";
            sto=Integer.parseInt( tbLis.getValueAt(fila, x++) +"");
            prec=Double.parseDouble(tbLis.getValueAt(fila, x++) +"");
            
        }
        
        txtId.setText(id_prod+"");
        txtCat.setText(cat);
        txtNombre.setText(nombre);
        txtSto.setText(sto+"");
        txtPrec.setText(prec+"");

        logicaProd.imprimir(tbLis);



    }//GEN-LAST:event_tbLisMouseClicked

    private void txtBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusActionPerformed

    private void txtBusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusKeyReleased
    
        
        
        logicaProd.imprimir(tbLis, txtBus.getText());
        
        
        
    }//GEN-LAST:event_txtBusKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        JFileChooser buscador = new JFileChooser();
     buscador.showOpenDialog(this);
     
     String rutaArch= buscador.getSelectedFile().getAbsolutePath();
     //logica carga el archivo en base de datos
     int resultados=logicaProd.cargaMasiva(rutaArch);
     
     if(resultados==0)
         JOptionPane.showMessageDialog(this, "No se pudo realizar la carga masiva");
     else
         JOptionPane.showMessageDialog(this, "Se registraron " + resultados+ " registros a la lista");
     
     
     logicaProd.imprimir(tbLis);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnImprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprActionPerformed
     logicaProd.generarReporte();
    }//GEN-LAST:event_btnImprActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElim;
    private javax.swing.JButton btnGuard;
    private javax.swing.JButton btnImpr;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnModi;
    private javax.swing.JButton btnSali;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLis;
    private javax.swing.JTextField txtBus;
    private javax.swing.JTextField txtCat;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrec;
    private javax.swing.JTextField txtSto;
    // End of variables declaration//GEN-END:variables

    
    
    
    
    
    private Productos getEntidad(){
        
        return new Productos(
                Integer.parseInt((txtId.getText().isEmpty())? "-1":txtId.getText()
        ),
                txtNombre.getText(),
                txtCat.getText(),
               
Integer.parseInt(txtSto.getText()),  
                Double.parseDouble(txtPrec.getText())
                
                
                );
 
                }
    
    
    

private boolean validaCampos(){
        
    boolean existeError=false;
    
    if(Utils._esVACIO(txtNombre.getText())){
            
            JOptionPane.showMessageDialog(this, "El nombre de producto no puede estar vacio");
        existeError=true;

    }
    
    else if(Utils._esVACIO(txtCat.getText())){
            
            JOptionPane.showMessageDialog(this, "La categoría no puede estar vacio");
        existeError=true;
    }
    
    else if(Utils._esVACIO(txtSto.getText())){
            
            JOptionPane.showMessageDialog(this, "La Stock no puede estar vacio");
        existeError=true; 
    }
    
    

    else if(Utils._esVACIO(txtPrec.getText())){
            
            JOptionPane.showMessageDialog(this, "El precio no puede estar vacio");
        existeError=true;
        
        }
        
        
        
        
    

    return existeError;
    }




}
